#!/usr/bin/env bash
set -eu

projects=(
  mediatoad
  morrigan
)

if ! [ -d "./src/test/java/com/vaguehope/common" ] ; then
  echo "not running in own dir."
  exit 1
fi

for project in ${projects[@]}; do
  dir="../$project"
  if ! [ -d "$dir" ] ; then
    echo "not a dir: $dir"
    exit 1
  fi

  echo "Project: $dir"

  shopt -s globstar
  for f in ./src/**/*.java; do
    target="$dir/$f"
    if [ -f "$target" ] ; then
      if ! cmp -s "$f" "$target" ; then
        cp -v "$f" "$target"
      fi
    fi
  done
done
